spring:
  profiles:
    include: keys
  jpa:
    hibernate.ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 50MB

logging:
  level:
    com.shoesbox: debug
    org:
      hibernate:
        type:
          descriptor:
            BasicBinder: trace
            #            sql: trace

default-images:
  thumbnail: https://i.ibb.co/Vj7Jrqx/default-thumbnail.webp
  profile: https://i.ibb.co/6wJFNWR/default-profile.webp
  friendPostDefaultImage: https://postfiles.pstatic.net/MjAyMjA5MzBfODcg/MDAxNjY0NTIzOTQwODE3.crRGRRD_63yKgHb8IPnc9e6F-ewXXeZ1paMA-gPHt6cg.XhC-AUQH46m96VY2A8DETCC3tIQgVj_rd6QpeJDSX5Qg.PNG.cinyoung92/%EC%9C%8C%EB%A0%88%EC%8A%A4.png?type=w966
