spring:
  profiles:
    include: keys
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        check_nullability: true
    defer-datasource-initialization: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 50MB

logging:
  level:
    com.shoesbox: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
            BasicBinder: trace

default-images:
  thumbnail: https://i.ibb.co/Vj7Jrqx/default-thumbnail.webp
  profile: https://i.ibb.co/6wJFNWR/default-profile.webp
